server:
  port: 9004

application:
  version : 1.0.0
  title : "Customer Serrvice"
######################## BANNER  ########################
spring:
  banner:
    charset : UTF-8
    location : classpath:banner.txt
######################## Conexion Mysql ########################
  jpa:
    database-platform : org.hibernate.dialect.MySQL8Dialect
    show-sql : true
    hibernate:
      ddl-auto : update
      naming:
        physical-strategy:org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false

mysql:
  service
    port:3306
    host:localhost
    username:admdb
    password:mancilla01

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  
  # -----------------  METRICAS ACTUATOR  ----------- #

management:
  endpoints:
    web:
      exposure:
        include: "*"
    shutdown:
      enabled: true
    health:
      enabled: true
    env:
      enabled: true
    auditevents:
      enabled: true
    flyway:
      enabled: true

 # -----------------  SERVICIO DE AUTODESCUBRIMIENTO  ----------- #
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:9002/eureka
        initialInstanceInfoReplicationIntervalSeconds: 5
        registryFetchIntervalSeconds: 5
    instance:
        leaseRenewalIntervalInSeconds: 5
        leaseExpirationDurationInSeconds: 5
