server:
  port: ${app.eureka-port}

application:
  version : 1.0.0
  title : "eureka Serrvice"
######################## BANNER  ########################
spring:
  banner:
    charset : UTF-8
    location : classpath:banner.txt

eureka:
  client: 
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:${app.eureka-port}/eureka/
  server:
    eviction-interval-timer-in-ms: 1000
    max.time.for.replication: 30000
    waitTimeInMsWhenSyncEmpty: 0
######################## SALUD  ########################
logging:
  com.netflix.discovery: 'ON'
  org.springframework.cloud: 'DEBUG'
management:
  endpoint:
    web:
      exposure:
        include: "*"
    health:
      enabled: true
      show-details: always
health:
  config:
    time-to-live: 30      
