server:
  port: ${app.eureka-port}

application:
  version : 1.0.0
  title : "eureka Serrvice"
######################## BANNER  ########################
spring:
  banner:
    charset : UTF-8
    location : classpath:banner.txt

eureka:
  instance:
    hostname: ${app.eureka-server}
    leaseRenewalintervalInSeconds: 30
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${app.eureka-server}:${app.eureka-port}/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 0
      response-cache-update-interval-ms: 5000
      enable-self-preservation: true
      renewalPercentThreshold: 0.49
######################## SALUD  ########################
management:
  endpoint:
    web:
      exposure:
        include: "*"
    health:
      enabled: true
      show-details: always
health:
  config:
    time-to-live: 30      
